### PR TITLE
Fix styles injection for custom stylesheets files

### LINKED ISSUE #222: index.scss injection
Maybe i'm wrong, but when running `gulp inject` or `gulp serve`, `*.scss` files from app and components directories should be injected into `app/index.scss` between `// injector` and `// endinjector` tags.

It seems it doesn't work, and styles defined in those files are not included in the webapp.

(Using master)

### PR DESCRIPTION
**Pull request by Toilal**
There were two problems related to `gulp-filter` to inject only in `index.scss` : 

- Sass compilation must be performed after `index.scss` injection.
- The filter pattern must be filename only `index.scss`, because default basepath of vinyl files is `src/app/`.

Close #222

### CODE REVIEW

File: app/templates/gulp/_styles.js [hunk 1]
```diff
@@ -40,12 +40,15 @@ gulp.task('styles', function () {
     addRootSlash: false
   };
 
-  var indexFilter = $.filter(paths.src + '/app/index.<%= props.cssPreprocessor.extension %>');
+  var indexFilter = $.filter('index.<%= props.cssPreprocessor.extension %>');
```
Comment (Toilal) [inline app/templates/gulp/_styles.js]: base directory of vynil files is `paths.src + '/app/'`, we don't need path in filter because globling is applied from base path only. (see https://github.com/wearefractal/vinyl/blob/master/README.md#optionsbase)

**Comment by Swiip** [comment]
Thanks
